# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/ai"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/discord"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/mongo"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/ws"
    schedule:
      interval: "weekly"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain Dockerfile content
  - package-ecosystem: "docker"
    directory: "/ai"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/discord"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/ws"
    schedule:
      interval: "weekly"
