# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python PyTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    environment:
      name: testing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start Redis
      uses: caiomarruda/redisearch-action@v1.0.1
      with:
        redis version: 2.6.0
    - name: Test with PyTest
      id: pytestext
      env:
          LOGURU_LEVEL:       ${{ secrets.SEP_LOGURU_LEVEL }}
          GUNICORN_CHDIR:     ${{ secrets.GUNICORN_CHDIR }}

          SEP_INTERNAL_TOKEN: ${{ secrets.SEP_INTERNAL_TOKEN }}
          SEP_SECRET_KEY:     ${{ secrets.SEP_SECRET_KEY }}

          SEP_SMTP_FROM:      ${{ secrets.SEP_SMTP_FROM }}
          SEP_SMTP_SERVER:    ${{ secrets.SEP_SMTP_SERVER }}
          SEP_SMTP_USER:      ${{ secrets.SEP_SMTP_USER }}
          SEP_SMTP_PASS:      ${{ secrets.SEP_SMTP_PASS }}
          SEP_SMTP_HOSTNAME:  ${{ secrets.SEP_SMTP_HOSTNAME }}
      run: |
        echo "--- Starting app in background"
        python3 api/app.py &
        echo "--- Sleep(3)"
        sleep 3
        echo "--- Starting PyTest [EXTERNAL]"
        pytest api/tests/external/test_0*.py api/tests/external/test_1*.py
        echo "--- Starting PyTest [INTERNAL]"
        pytest -s api/tests/internal
        echo "--- Starting PyTest [EXTERNAL] (Cleaning)"
        pytest api/tests/external/test_99*.py
